### ISSUE TITLE
Nothing happen after Push File

### ISSUE THREAD

**Issue by wchuan11** [adamyeager/PushbulletSharp#1]
When preview the URL in browser, HTTP error 403 is displayed.

Everything looks OK when stepping through.

The code I written on VB:

Private Sub PushFile()
        Dim Client As New PushbulletClient(ApiKey)
        Dim request As New PushFileRequest() With { _
  .device_iden = "xxxxxxxxxxx", _
  .file_type = "image/png", _
  .file_name = "image.png", _
  .file_path = Application.StartupPath & "\" & "image.png"
  }
        Dim response = Client.PushFile(request)
        MsgBox("pushed")
End Sub

Am I misssing anything?

**Comment by adamyeager** [comment]
Yes, the file pushing is incomplete. I really should have put a not implemented exception on that part. I haven't had time lately to finishing it, but let me see if I can complete it this weekend.

**Comment by adamyeager** [comment]
Hi @wchuan11 
I have fixed the file pushing functionality. I've tested it by pushing an image to my iOS device. Please let me know if you have any more issues.

Also, I added a property to the PushFileRequest class for "body" which is an optional parameter according to PushBullet's API.

**Comment by wchuan11** [comment]
Thumbs up!
