### ISSUE TITLE
Support for Channels

### ISSUE THREAD

**Issue by nemec** [adamyeager/PushbulletSharp#10]
Pushbullet has added support for "channels", a way for people to subscribe to a category of pushes. It would be nice, at the very least, to be able to include a channel tag in a push so that others listening to the channel will see the updates.

https://docs.pushbullet.com/#create-push

**Comment by adamyeager** [comment]
Thanks for submitting an issue. I will take a look into this as soon as I can.

**Comment by adamyeager** [comment]
This update was completed by another github user with pull request #11. ChannelTag is now on all push requests. This will be released with 2.2.0.

**Comment by nemec** [comment]
Thanks!
