### ISSUE TITLE
Mono Issue

### ISSUE THREAD

**Issue by DunkyG** [adamyeager/PushbulletSharp#16]
When I try to get the client info using your library under mono I get the following error.
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-10)

> System.ArgumentException: Kind property of dateTime is Utc but the sourceTimeZone does not equal TimeZoneInfo.Utc
>   at System.TimeZoneInfo.ConvertTime (DateTime dateTime, System.TimeZoneInfo sourceTimeZone, System.TimeZoneInfo destinationTimeZone) [0x00000] in <filename unknown>:0
>   at System.TimeZoneInfo.ConvertTime (DateTime dateTime, System.TimeZoneInfo destinationTimeZone) [0x00000] in <filename unknown>:0
>   at PushbulletSharp.PushbulletClient.ConvertFromBasicSubscription (PushbulletSharp.Models.Responses.BasicSubscription basicSubscription) [0x00000] in <filename unknown>:0
>   at PushbulletSharp.PushbulletClient.CurrentUsersSubscriptions (Boolean showActiveOnly) [0x00000] in <filename unknown>:0

**Comment by adamyeager** [comment]
I'm not too familiar with Mono, but let me ask you this, when you create your Client object are you using the optional parameter for TimeZoneInfo on the Client constructor?

`var myClient = new PushbulletClient("APIKEY", TimeZoneInfo.Local);`
