### ISSUE TITLE
SMS Ephemeral

### ISSUE THREAD

**Issue by hanc2006** [adamyeager/PushbulletSharp#17]
Hi,
is possibile send SMS using the API https://api.pushbullet.com/v2/ephemerals?

**Comment by adamyeager** [comment]
Ephemerals have not been implemented yet for PushbulletSharp. I can look into it though.

**Comment by Broly-Dev** [comment]
Any news on adding ephemerals? Would love to see this. Thanks.

**Comment by adamyeager** [comment]
I know it's been a while since I've updated this project. I am actively working on making updates to match the latest version of the API. Ephemerals will be a part of this update.

**Comment by adamyeager** [comment]
I just wanted to update everyone that I've made a lot of progress with Ephemeral support. My working build now has end to end encryption support and this morning I successfully sent an encrypted ephemeral SMS txt to myself.

I'm trying to make the encryption part as easy as possible. There will be a new constructor for the Client itself where you can provide the user's encryption password. In the background it will find the user's iden and create a key for encryption. When sending encrypted messages you will only have to pass an optional boolean parameter to indicate that you want encryption. As long as a password was provided, encryption will happen automatically.

I'm hoping to have a new release out in the next few days to a week.

**Comment by adamyeager** [comment]
PushbulletSharp version 3.0 will be out tonight. It has full support for ephemerals. I have added unit tests to show how they work. I'm compiling the nuget package now.
