### ISSUE TITLE
 Dim devices = Client.CurrentUsersActiveDevices() is no member of PushbulletSharp

### ISSUE THREAD

**Issue by Semiconductor64** [adamyeager/PushbulletSharp#18]
Good day,

I am trying to use PushbulletSharp for VB.Net

Following line gives me an error although I did import PushbulletSharp into my VB Project.

 Dim devices = Client.CurrentUsersActiveDevices()

Error: CurrentUsersActiveDevices is no member of PushbulletClient

**Comment by adamyeager** [comment]
The Client does not have a method with the signature of CurrentUsersActiveDevices(). It does however have a method called 'CurrentUsersDevices' and it takes a bool for showing only active devices.

In C# it would be: 
UserDevices devices = Client.CurrentUsersDevices(true);

Does this help?
