### ISSUE TITLE
Bullet Contacts no longer supported

### ISSUE THREAD

**Issue by deuang** [adamyeager/PushbulletSharp#19]
Bullet no longer supports contact but changed to chat.  Are there any plans to update this to support the new features?

**Comment by adamyeager** [comment]
I know it's been a while since I've updated this project. I am actively working on making updates to match the latest version of the API. I will be adding Chat support.

**Comment by adamyeager** [comment]
PushbulletSharp version 3.0 will be out tonight. It has full support for chats. I have added unit tests to show how they work. I'm compiling the nuget package now.
