### ISSUE TITLE
Issue sending unecrypted Ephemeral Notification Request

### ISSUE THREAD

**Issue by khm971** [adamyeager/PushbulletSharp#22]
Hi, Adam, and thank you for the excellent wrapper!

I wanted to share what I think is a bug in the new Ephemeral Push code.  The below statement works great:
Dim Result As String = client.PushEphemeral(NotificationRequest, True)

However, this:
Dim Result As String = client.PushEphemeral(NotificationRequest, False)
results in the following error:

Type 'PushbulletSharp.Models.Requests.Ephemerals.NotificationEphemeral' with data contract name 'NotificationEphemeral:http://schemas.datacontract.org/2004/07/PushbulletSharp.Models.Requests.Ephemerals' is not expected. Consider using a DataContractResolver if you are using DataContractSerializer or add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to the serializer.

And I believe it's happening here:

 public static class PushbulletSharpExtensions
    {
        /// <summary>
        /// To the json.
        /// </summary>
        /// <param name="data">The data.</param>
        /// <returns></returns>
        public static string ToJson(this object data)
        {
            var serializer = new DataContractJsonSerializer(data.GetType());

            using (MemoryStream stream = new MemoryStream())
            {
                serializer.WriteObject(stream, data);   // **** OFFENDING CODE ******
                return Encoding.UTF8.GetString(stream.ToArray(), 0, (int)stream.Length);
            }
        }

Hopefully that's useful information.  If you'd like any more info, just let me know, and thanks for all of your work!

**Comment by adamyeager** [comment]
Good catch, and sorry that it's happening. I've got family in town today, and I should be free to look into the issue tomorrow. Hopefully I'll have it resolved for you in the next couple of days.

I'm glad to hear you're enjoying this library! :)

**Comment by khm971** [comment]
Hi, Adam,

Thanks for the quick reply.  Yes, I sure do enjoy your library, made my life so much easier and my code so much cleaner than the mess I was making on my own.

Enjoy your time with the family!

/\KHM

**Comment by adamyeager** [comment]
I've fixed this issue and it will be included in the next release (3.1). I have one other issue to finish and then I will push it to nuget.

**Comment by khm971** [comment]
Thanks, Adam!

/\KHM

**Comment by emanuelgaspar** [comment]
Hi Adam.

First of all, thanks for your great work with this package.

Having faced the "data contract name" issue just now, I'm writing this message as a friendly ping to remind you to release the new 3.1 version.

Thanks,
Emanuel

**Comment by adamyeager** [comment]
I just uploaded a new version of PushbulletSharp to nuget (3.1.0). It should show up very soon and it addresses this issue.
