### ISSUE TITLE
PushList - HTTP400

### ISSUE THREAD

**Issue by codebude** [adamyeager/PushbulletSharp#25]
At first - thanks for the nice library. Unfortunately the PushList-example doesn't work any longer. It gets an HTTP400 error, asking for missing parameters.

**Comment by adamyeager** [comment]
Thanks for pointing this out. I'll take a look at the issue when I get a free moment.

**Comment by anarfox** [comment]
Same for PushNote.

**Comment by codebude** [comment]
@anarfox That's strange. PushNote is still working for me. So maybe these are geo or time-based restrictions/errors?

**Comment by frogwild** [comment]
I installed today. I have PushNote working but PushAddress and PushList are getting the exception 400 for me.

**Comment by adamyeager** [comment]
According to the Pushbullet API documentation, address and list have been deprecated and are no longer supported.

> January 28, 2015
> Removed address and list pushes which have been deprecated for forever.

It's in the changelog at the bottom. I'll work on removing it from PushbulletSharp.

**Comment by frogwild** [comment]
OK. Great. Thanks for clearing that up.

**Comment by adamyeager** [comment]
I just uploaded a new version of PushbulletSharp to nuget (3.1.0). It should show up very soon and it addresses this issue.
