### ISSUE TITLE
Add Happy Birthday Functionality?

### ISSUE THREAD

**Issue by SomethingNew71** [adamyeager/PushbulletSharp#27]
╮╭╭╮┏╮┏╮╮╭┊┊┊┊┊┊┊
┣┫┣┫┣╯┣╯╰┫┊┊☆☆┊┊┊
╯╯╯╯╯┊╯┊╰╯╭━┻┻━╮┊
┏╮┊┏╮╭╮╮╭╭┻━━━━┻╮
┣┫★┃┃┣┫╰┫┣╮╭╮╭╮╭┫
┗╯┊┗╯╯╯╰╯┃╰╯╰╯╰╯┃
━━━━━━━━━╯╳╳╳╳╳╳╰

**Comment by adamyeager** [comment]
I can't even.
