### ISSUE TITLE
Modified date required

### ISSUE THREAD

**Issue by damianon** [adamyeager/PushbulletSharp#8]
Why is the modified_date a required parameter? Pushbullet API specifies it as optional. 
Which posts are returned when the parameter is not specified? The most recent ones? Because that would be more useful than specifying a modified_date

**Comment by damianon** [comment]
Also I just noticed the cursor parameter is not available from the GetPushes() method as return and neither as parameter

**Comment by adamyeager** [comment]
Good catch, I will look into these issues later when I get home from work.

**Comment by adamyeager** [comment]
These issues should be fixed now with the latest 2.1.0 release. Please let me know if there are still problems.
